export default {
  GET_ADMIN: "GET_ADMIN",
  GET_ADMIN_RECEIVE: "GET_ADMIN_RECEIVE",
  GET_ADMIN_ALL: "GET_ADMIN_ALL",
  GET_ADMIN_ALL_RECEIVE: "GET_ADMIN_ALL_RECEIVE",
  GET_ADMIN_ALL_BY_CITY: "GET_ADMIN_ALL_BY_CITY",
  GET_ADMIN_ALL_BY_CITY_RECEIVE:
    "GET_ADMIN_GET_ADMIN_ALL_BY_CITY_RECEIVEALL_RECEIVE",
  GET_ADMIN_BY_NAMES: "GET_ADMIN_BY_NAMES",
  GET_ADMIN_BY_NAMES_RECEIVE: "GET_ADMIN_BY_NAMES_RECEIVE",
  ADD_ADMIN: "ADD_ADMIN",
  DELETE_ADMIN: "DELETE_ADMIN",
  UPDATE_ADMIN: "UPDATE_ADMIN",
  LOADING_ADMIN: "LOADING_ADMIN",
  RESET_ADMIN: "RESET_ADMIN",
};
