export default {
  ON_SIGN_IN: "ON_SIGN_IN",
  ON_SIGN_IN_RECEIVE: "ON_SIGN_IN_RECEIVE",
  ON_SIGN_UP: "ON_SIGN_UP",
  ON_RECOVER: "ON_RECOVER",
  ON_RECOVER_RECEIVE:"ON_RECOVER_RECEIVE",
  LOADING_AUTH: "LOADING_AUTH",
  RESET_AUTH: "RESET_AUTH",
};
