export default {
  GET_BILL: "GET_BILL",
  GET_BILL_RECEIVE: "GET_BILL_RECEIVE",
  GET_BILLS_BY_USER: "GET_BILL_BY_USER",
  GET_BILLS_BY_PROVIDER: "GET_BILLS_BY_PROVIDER",
  GET_BILLS_ALL_RECEIVE: "GET_BILLS_ALL_RECEIVE",
  ADD_BILL: "ADD_BILL",
  DELETE_BILL: "DELETE_BILL",
  UPDATE_BILL: "UPDATE_BILL",
  LOADING_BILL: "LOADING_BILL",
  RESET_BILL: "RESET_BILL",
};
