export default {
  GET_CITY: "GET_CITY",
  GET_CITY_BY_NAME: "GET_CITY_BY_NAME",
  GET_CITY_RECEIVE: "GET_CITY_RECEIVE",
  GET_CITIES_ALL: "GET_CITIES_ALL",
  GET_CITIES_ALL_RECEIVE: "GET_CITIES_ALL_RECEIVE",
  ADD_CITY: "ADD_CITY",
  DELETE_CITY: "DELETE_CITY",
  UPDATE_CITY: "UPDATE_CITY",
  LOADING_CITY: "LOADING_CITY",
  RESET_CITY: "RESET_CITY",
};
