export default {
  ON_LOGIN: "ON_LOGIN",
  ON_LOGIN_RECEIVE: "ON_LOGIN_RECEIVE",
  LOADING_LOGIN: "LOADING_LOGIN",
  RESET_LOGIN: "RESET_LOGIN",

  GET_PROVIDER: "GET_PROVIDER",
  GET_PROVIDER_RECEIVE: "GET_PROVIDER_RECEIVE",
  LOADING_PROVIDER: "LOADING_PROVIDER",
  RESET_PROVIDER: "RESET_PROVIDER",
};