export const ON_LOGIN = "ON_LOGIN";
export const ON_LOGIN_RECEIVE = "ON_LOGIN_RECEIVE";
export const LOADING_LOGIN = "LOADING_LOGIN";
export const RESET_LOGIN = "RESET_LOGIN";
export const GET_PROVIDER_INFO = "GET_PROVIDER_INFO";
export const GET_PROVIDER_INFO_RECEIVE = "GET_PROVIDER_INFO_RECEIVE";
