export default {
  GET_USER: "GET_USER",
  GET_USER_RECEIVE: "GET_USER_RECEIVE",
  GET_USER_ALL: "GET_USER_ALL",
  GET_USER_ALL_RECEIVE: "GET_USER_ALL_RECEIVE",
  GET_USER_BY_POINTS: "GET_USER_BY_POINTS",
  GET_USER_BY_POINTS_RECEIVE: "GET_USER_BY_POINTS_RECEIVE",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  LOADING_USER: "LOADING_USER",
  RESET_USER: "RESET_USER",
};
